### ISSUE TITLE
useRequest CORS issue

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#85]
For some reason useRequest doesn't work for a prismic url, where fetch does. Seems like there are some headers being set under the hood in useRequest but I couldn't quickly figure out where.
useRequest results in an options request, but the get request is never made at all. The get request from `fetch` is successful.

https://github.com/inputlogic/pwa-starter/tree/pris see the /users route to replicate

```
  // This doesn't work
  const { result } = useRequest(store, 'https://inputcowork.cdn.prismic.io/api/v2/documents/search?ref=Xkw20hAAACQAJcMX')

  // This works
  useEffect(() => {
    fetch('https://inputcowork.cdn.prismic.io/api/v2/documents/search?ref=Xkw20hAAACQAJcMX')
      .then(res => res.json())
      .then(json => console.log(json))
  }, [])

```

<img width="1019" alt="Screen Shot 2020-03-02 at 3 08 18 PM" src="https://user-images.githubusercontent.com/5009842/75726773-0eb8d500-5c98-11ea-9247-d184512fed89.png">

**Comment by staydecent** [comment]
The issue is because useRequest assumes JSON as the content type and automatically sets that header for `Content-Type` which results in the request **not** fitting the criteria to be a [Simple Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests).

(in your case, the `Authorization` header was also being sent.)

Because the request is not a Simple Request, the browser sends a CORS preflight request, which contains those headers (authorization and content-type) which Prismic is **not** setup to handle. Meaning, Prismic is not allowing these headers for OPTIONS requests in their CORS configuration. 

The reason the fetch works, is because no headers are being set, so it results in a Simple Request, foregoing the need for an OPTIONS preflight. Further, Prismic's servers are set to return JSON without us needing to request that Content-Type.

Ultimately, this is a fault in Prismic's CORS configuration. But, we can add more flexibility to useRequest to work around this issue. (I'll get a PR out today)

@coryschadt @adriaanwm
